#!/usr/bin/env bash
# Launcher tests for run.sh. Starts throwaway stacks from tests/fixture in a temp folder
# and removes them again. Needs Docker, plus python3, python or PowerShell for the
# native listener. Ports 18080 to 18087 and 18095 must be free.
#   tests/test.sh
set -u
ROOT=$(cd "$(dirname "$0")/.." && pwd)
WORK=$(mktemp -d)
ID=cltest-$$
FAILS=0
OUT=
LISTENER_PID=

is_busy() { (exec 3<>"/dev/tcp/127.0.0.1/$1") 2>/dev/null; }

check() { # check <description> <command...>
  desc=$1; shift
  if "$@"; then echo "  ok   $desc"; return; fi
  echo "  FAIL $desc"
  FAILS=$((FAILS + 1))
  # Show the output of the last launcher call once, to explain the failure.
  if [ -n "$OUT" ]; then printf '%s
' "$OUT" | sed 's/^/       | /'; OUT=; fi
}
contains() { case $1 in *"$2"*) return 0 ;; esac; return 1; }
distinct() { [ "$(printf '%s\n' "$@" | sort -u | wc -l)" -eq $# ]; }

stack_dir() { echo "$WORK/$ID-$1"; }
new_stack() {
  mkdir "$(stack_dir "$1")"
  cp "$ROOT/tests/fixture/docker-compose.yml" "$ROOT/tests/fixture/run.conf" "$(stack_dir "$1")/"
}
launch() { # launch <stack> [args...]: sets OUT and RC
  s=$1; shift
  OUT=$(cd "$(stack_dir "$s")" && bash "$ROOT/run.sh" "$@" 2>&1); RC=$?
}
compose() { s=$1; shift; (cd "$(stack_dir "$s")" && docker compose "$@" 2>/dev/null); }
env_of() { sed -n "s/^$2=//p" "$(stack_dir "$1")/.env" | tail -n 1; }
is_running() { [ -n "$(compose "$1" ps --status running -q)" ]; }

wait_port() { # wait_port <port> busy|free
  for _ in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20; do
    if is_busy "$1"; then [ "$2" = busy ] && return 0; else [ "$2" = free ] && return 0; fi
    sleep 0.5
  done
  return 1
}
start_listener() { # a native process (no container) that accepts connections on 127.0.0.1:<port>
  py="import socket;s=socket.socket();s.bind(('127.0.0.1',$1));s.listen(5)
while 1: s.accept()[0].close()"
  ps="\$l=[Net.Sockets.TcpListener]::new([Net.IPAddress]::Loopback,$1);\$l.Start();while(1){\$l.AcceptTcpClient().Close()}"
  if python3 -c '' 2>/dev/null; then python3 -c "$py" &
  elif python -c '' 2>/dev/null; then python -c "$py" &
  elif command -v pwsh >/dev/null; then pwsh -NoProfile -Command "$ps" &
  elif command -v powershell.exe >/dev/null; then powershell.exe -NoProfile -Command "$ps" &
  else echo "No python3, python or PowerShell found for the native listener." >&2; exit 2
  fi
  LISTENER_PID=$!
  LISTENER_PORT=$1
  wait_port "$1" busy || { echo "The native listener did not start on port $1." >&2; exit 2; }
}
stop_listener() {
  [ -n "$LISTENER_PID" ] || return 0
  kill "$LISTENER_PID" 2>/dev/null
  wait "$LISTENER_PID" 2>/dev/null
  LISTENER_PID=
  wait_port "$LISTENER_PORT" free
}

cleanup() {
  for dir in "$WORK"/*/; do
    [ -d "$dir" ] && (cd "$dir" && docker compose down -v --remove-orphans >/dev/null 2>&1)
  done
  stop_listener
  rm -rf "$WORK"
}
trap cleanup EXIT

for port in 18080 18081 18082 18083 18084 18085 18086 18087 18095; do
  if is_busy "$port"; then echo "Port $port is busy: the tests need 18080 to 18087 and 18095 free." >&2; exit 2; fi
done
for s in a b c d; do new_stack "$s"; done

echo "1. A native process on the default port is skipped"
start_listener 18080
launch a
check "exit code 0" test "$RC" = 0
check "reports WEB_PORT moving off 18080" contains "$OUT" "WEB_PORT: port 18080 is busy, using 18081"
check "reports ADMIN_PORT skipping the port picked for WEB_PORT" contains "$OUT" "ADMIN_PORT: port 18081 is busy, using 18082"
check ".env starts with the generated header" contains "$(head -n 1 "$(stack_dir a)/.env")" "# Generated by run.sh"
check ".env has WEB_PORT=18081" test "$(env_of a WEB_PORT)" = 18081
check ".env has ADMIN_PORT=18082" test "$(env_of a ADMIN_PORT)" = 18082
check "prints the web URL" contains "$OUT" "Web:   http://localhost:18081"
check "prints the admin URL" contains "$OUT" "Admin: http://localhost:18082"
check "the stack is running" is_running a
check "the stack answers on the chosen port" wait_port 18081 busy

echo "2. Rerun while the stack is running"
before_env=$(cat "$(stack_dir a)/.env")
before_ids=$(compose a ps -q)
launch a
check "exit code 0" test "$RC" = 0
check "says the stack is already running" contains "$OUT" "Stack already running: leaving ports unchanged and skipping the rebuild."
check ".env is unchanged" test "$(cat "$(stack_dir a)/.env")" = "$before_env"
check "the container was not recreated" test "$(compose a ps -q)" = "$before_ids"
check "prints the web URL again" contains "$OUT" "Web:   http://localhost:18081"

echo "3. A second and a third stack started back to back"
launch b
check "second stack: exit code 0" test "$RC" = 0
launch c
check "third stack: exit code 0" test "$RC" = 0
check "all three stacks are running" eval 'is_running a && is_running b && is_running c'
check "the six ports are all different" distinct "$(env_of a WEB_PORT)" "$(env_of a ADMIN_PORT)" \
  "$(env_of b WEB_PORT)" "$(env_of b ADMIN_PORT)" "$(env_of c WEB_PORT)" "$(env_of c ADMIN_PORT)"
check "nobody took the native process's port" eval '! contains " $(env_of a WEB_PORT) $(env_of b WEB_PORT) $(env_of c WEB_PORT) " " 18080 "'

echo "4. A stale .env is re-validated once the stack is stopped"
launch a down
check "arguments are passed to docker compose (down): exit code 0" test "$RC" = 0
check "the first stack is stopped" eval '! is_running a'
check "the other stacks keep running" eval 'is_running b && is_running c'
stop_listener
start_listener 18081
launch a
check "exit code 0" test "$RC" = 0
check "reports the stale WEB_PORT as busy" contains "$OUT" "WEB_PORT: port 18081 is busy"
check "WEB_PORT moved off 18081" eval '[ "$(env_of a WEB_PORT)" != 18081 ]'
check "the six ports are still all different" distinct "$(env_of a WEB_PORT)" "$(env_of a ADMIN_PORT)" \
  "$(env_of b WEB_PORT)" "$(env_of b ADMIN_PORT)" "$(env_of c WEB_PORT)" "$(env_of c ADMIN_PORT)"
check "the first stack is running again" is_running a

echo "5. An existing .env with custom values keeps them"
printf '# my settings\r\nSECRET=keep=me\r\nWEB_PORT=18095\r\nOTHER=1' > "$(stack_dir d)/.env"
launch d config --quiet
check "arguments are passed to docker compose (config --quiet): exit code 0" test "$RC" = 0
check "no port message for the pinned free port" eval '! contains "$OUT" "WEB_PORT"'
printf '# my settings\r\nSECRET=keep=me\r\nWEB_PORT=18095\r\nOTHER=1\nADMIN_PORT=%s\n' "$(env_of d ADMIN_PORT)" > "$WORK/expected.env"
check "every existing byte is kept and only ADMIN_PORT is appended" cmp -s "$(stack_dir d)/.env" "$WORK/expected.env"

echo "6. share refuses a project with more than one port"
launch d share
check "exit code 1" test "$RC" = 1
check "names the ports in the message" contains "$OUT" "share needs exactly one port in run.conf, this project has 2: WEB_PORT ADMIN_PORT"
check "nothing was started" eval '! is_running d'

echo
if [ "$FAILS" -eq 0 ]; then echo "All checks passed."; else echo "$FAILS check(s) failed."; exit 1; fi
