# Launcher tests for run.ps1. Starts throwaway stacks from tests/fixture in a temp folder
# and removes them again. Needs Docker. Ports 18080 to 18087 and 18095 must be free.
# Works in PowerShell 7 and Windows PowerShell 5.1: the launcher runs in the same edition.
#   .\tests\test.ps1
$ErrorActionPreference = 'Stop'
$Root = Split-Path -Parent $PSScriptRoot
$Shell = (Get-Process -Id $PID).Path
$Id = "cltest-$PID"
$Work = Join-Path ([IO.Path]::GetTempPath()) $Id
$script:Fails = 0
$script:Listener = $null
$script:LastOutput = @()

function Test-PortBusy([int]$Port) {
    $client = New-Object Net.Sockets.TcpClient
    try {
        $wait = $client.BeginConnect('127.0.0.1', $Port, $null, $null)
        return ($wait.AsyncWaitHandle.WaitOne(500) -and $client.Connected)
    } catch { return $false } finally { $client.Close() }
}

function Check([string]$Description, [bool]$Ok) {
    if ($Ok) { Write-Host "  ok   $Description"; return }
    Write-Host "  FAIL $Description"
    $script:Fails++
    # Show the output of the last launcher call once, to explain the failure.
    foreach ($line in $script:LastOutput) { Write-Host "       | $line" }
    $script:LastOutput = @()
}
function Test-Distinct([string[]]$Values) { @($Values | Sort-Object -Unique).Count -eq $Values.Count }

# Runs a native command with stderr merged into the returned lines. Windows PowerShell 5.1
# turns redirected stderr into errors, so the preference is relaxed around the call.
function Invoke-Native([scriptblock]$Command) {
    $ErrorActionPreference = 'Continue'
    & $Command 2>&1 | ForEach-Object { "$_" }
}

function Get-StackDir([string]$Stack) { Join-Path $Work "$Id-$Stack" }
function New-Stack([string]$Stack) {
    $dir = Get-StackDir $Stack
    New-Item -ItemType Directory -Path $dir | Out-Null
    Copy-Item (Join-Path $Root 'tests/fixture/docker-compose.yml'), (Join-Path $Root 'tests/fixture/run.conf') $dir
}
function Invoke-Launcher([string]$Stack) {
    $script = Join-Path $Root 'run.ps1'
    $launcherArgs = $args
    Push-Location (Get-StackDir $Stack)
    try {
        $lines = Invoke-Native { & $Shell -NoProfile -ExecutionPolicy Bypass -File $script @launcherArgs }
    } finally { Pop-Location }
    $script:LastOutput = @($lines)
    @{ Output = ($lines -join "`n"); ExitCode = $LASTEXITCODE }
}
function Invoke-Compose([string]$Stack) {
    $composeArgs = $args
    Push-Location (Get-StackDir $Stack)
    try { Invoke-Native { docker compose @composeArgs 2>$null } } finally { Pop-Location }
}
function Get-EnvBytes([string]$Stack) { [IO.File]::ReadAllText((Join-Path (Get-StackDir $Stack) '.env')) }
function Get-EnvOf([string]$Stack, [string]$Key) {
    $hit = [regex]::Matches((Get-EnvBytes $Stack), "(?m)^$Key=([^\r\n]*)") | Select-Object -Last 1
    if ($hit) { $hit.Groups[1].Value } else { '' }
}
function Test-Running([string]$Stack) { [bool](Invoke-Compose $Stack ps --status running -q) }
function Get-AllPorts { foreach ($s in 'a', 'b', 'c') { Get-EnvOf $s WEB_PORT; Get-EnvOf $s ADMIN_PORT } }

# A native listener (no container) that accepts connections on 127.0.0.1:<port>.
function Start-Listener([int]$Port) {
    $script:Listener = [Net.Sockets.TcpListener]::new([Net.IPAddress]::Loopback, $Port)
    $script:Listener.Start()
}
function Stop-Listener {
    if ($script:Listener) { $script:Listener.Stop(); $script:Listener = $null }
}

try {
    foreach ($port in 18080..18087 + 18095) {
        if (Test-PortBusy $port) { Write-Host "Port $port is busy: the tests need 18080 to 18087 and 18095 free."; exit 2 }
    }
    New-Item -ItemType Directory -Path $Work | Out-Null
    foreach ($s in 'a', 'b', 'c', 'd') { New-Stack $s }

    Write-Host '1. A native process on the default port is skipped'
    Start-Listener 18080
    $r = Invoke-Launcher a
    Check 'exit code 0' ($r.ExitCode -eq 0)
    Check 'reports WEB_PORT moving off 18080' $r.Output.Contains('WEB_PORT: port 18080 is busy, using 18081')
    Check 'reports ADMIN_PORT skipping the port picked for WEB_PORT' $r.Output.Contains('ADMIN_PORT: port 18081 is busy, using 18082')
    Check '.env starts with the generated header' (Get-EnvBytes a).StartsWith('# Generated by run.ps1')
    Check '.env has WEB_PORT=18081' ((Get-EnvOf a WEB_PORT) -eq '18081')
    Check '.env has ADMIN_PORT=18082' ((Get-EnvOf a ADMIN_PORT) -eq '18082')
    Check 'prints the web URL' $r.Output.Contains('Web:   http://localhost:18081')
    Check 'prints the admin URL' $r.Output.Contains('Admin: http://localhost:18082')
    Check 'the stack is running' (Test-Running a)
    Check 'the stack answers on the chosen port' (Test-PortBusy 18081)

    Write-Host '2. Rerun while the stack is running'
    $beforeEnv = Get-EnvBytes a
    $beforeIds = (Invoke-Compose a ps -q) -join ' '
    $r = Invoke-Launcher a
    Check 'exit code 0' ($r.ExitCode -eq 0)
    Check 'says the stack is already running' $r.Output.Contains('Stack already running: leaving ports unchanged and skipping the rebuild.')
    Check '.env is unchanged' ((Get-EnvBytes a) -ceq $beforeEnv)
    Check 'the container was not recreated' (((Invoke-Compose a ps -q) -join ' ') -eq $beforeIds -and $beforeIds)
    Check 'prints the web URL again' $r.Output.Contains('Web:   http://localhost:18081')

    Write-Host '3. A second and a third stack started back to back'
    Check 'second stack: exit code 0' ((Invoke-Launcher b).ExitCode -eq 0)
    Check 'third stack: exit code 0' ((Invoke-Launcher c).ExitCode -eq 0)
    Check 'all three stacks are running' ((Test-Running a) -and (Test-Running b) -and (Test-Running c))
    Check 'the six ports are all different' (Test-Distinct (Get-AllPorts))
    Check "nobody took the native process's port" ((Get-AllPorts) -notcontains '18080')

    Write-Host '4. A stale .env is re-validated once the stack is stopped'
    $r = Invoke-Launcher a down
    Check 'arguments are passed to docker compose (down): exit code 0' ($r.ExitCode -eq 0)
    Check 'the first stack is stopped' (-not (Test-Running a))
    Check 'the other stacks keep running' ((Test-Running b) -and (Test-Running c))
    Stop-Listener
    Start-Listener 18081
    $r = Invoke-Launcher a
    Check 'exit code 0' ($r.ExitCode -eq 0)
    Check 'reports the stale WEB_PORT as busy' $r.Output.Contains('WEB_PORT: port 18081 is busy')
    Check 'WEB_PORT moved off 18081' ((Get-EnvOf a WEB_PORT) -ne '18081')
    Check 'the six ports are still all different' (Test-Distinct (Get-AllPorts))
    Check 'the first stack is running again' (Test-Running a)

    Write-Host '5. An existing .env with custom values keeps them'
    $custom = "# my settings`r`nSECRET=keep=me`r`nWEB_PORT=18095`r`nOTHER=1"
    [IO.File]::WriteAllText((Join-Path (Get-StackDir d) '.env'), $custom, (New-Object Text.UTF8Encoding $false))
    $r = Invoke-Launcher d config --quiet
    Check 'arguments are passed to docker compose (config --quiet): exit code 0' ($r.ExitCode -eq 0)
    Check 'no port message for the pinned free port' (-not $r.Output.Contains('WEB_PORT'))
    Check 'every existing byte is kept and only ADMIN_PORT is appended' ((Get-EnvBytes d) -ceq "$custom`nADMIN_PORT=$(Get-EnvOf d ADMIN_PORT)`n")
} finally {
    if (Test-Path $Work) {
        foreach ($dir in Get-ChildItem -Directory $Work) {
            Push-Location $dir.FullName
            try { Invoke-Native { docker compose down -v --remove-orphans } | Out-Null } finally { Pop-Location }
        }
    }
    Stop-Listener
    if (Test-Path $Work) { Remove-Item -Recurse -Force $Work }
}

Write-Host ''
if ($script:Fails -eq 0) { Write-Host 'All checks passed.' } else { Write-Host "$($script:Fails) check(s) failed."; exit 1 }
